---STORE ANALYSIS:
-------------------------------------------------------------------------
---1. Query to check if the table is loaded correctly 
-------------------------------------------------------------------------
select * from `brightlight`.`default`.`bright_coffee_shop_analysis`;

-------------------------------------------------------------------------
--2.Checking the date range
-------------------------------------------------------------------------
--Data collection start date? (2023-01-01)

SELECT MIN(transaction_date) AS start_date
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

-------------------------------------------------------------------------
--3.What is the last date for data collection? (2023-06-01)
-------------------------------------------------------------------------

SELECT MAX(transaction_date) AS latest_date
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

-------------------------------------------------------------------------
--4.Checking the names of store location
-------------------------------------------------------------------------
-- There are 3 store locations; Lower Manhattan, Hell's Kitchen and Astoria

SELECT DISTINCT store_location,
                store_id
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

-------------------------------------------------------------------------
--5.Checking store trasactional data
-------------------------------------------------------------------------
SELECT DISTINCT store_location,
                COUNT (transaction_id) AS transaction_Count
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY store_location
ORDER BY transaction_Count DESC;

-------------------------------------------------------------------------
--6.Check total_amount by store_location
-------------------------------------------------------------------------
SELECT DISTINCT store_location,
        SUM (unit_price * transaction_qty) AS total_amount
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY store_location
ORDER BY total_amount DESC;

---PRODUCT ANALYSIS
-------------------------------------------------------------------------
--7. Check which products are sold across each store
-------------------------------------------------------------------------
SELECT DISTINCT product_category
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

-------------------------------------------------------------------------
--8.Checking which product information in the dataset
-------------------------------------------------------------------------
SELECT DISTINCT product_category AS category,
                product_detail AS product_name
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

-------------------------------------------------------------------------
--9.Checking which product information in the dataset
-------------------------------------------------------------------------
SELECT DISTINCT product_type
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

-------------------------------------------------------------------------
--10.Checking which product information in the dataset
-------------------------------------------------------------------------

SELECT DISTINCT product_category AS category,
                product_type,
                product_detail AS product_name
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

-------------------------------------------------------------------------
---11.product count to retrieve products that are most purchased
-------------------------------------------------------------------------
SELECT product_category,
       COUNT(product_id) AS number_of_transactions
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY product_category
ORDER BY number_of_transactions DESC;

-------------------------------------------------------------------------
--12.Top 5 products that have generated the highest revenue
-------------------------------------------------------------------------
SELECT DISTINCT product_type, 
                MAX(unit_price * transaction_qty) AS max_total_Revenue
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY product_type
ORDER BY max_total_Revenue DESC
LIMIT 1;

-------------------------------------------------------------------------
--13.Top 5 products that have generated the lowest revenue
-------------------------------------------------------------------------
SELECT DISTINCT product_type, 
                MIN(unit_price * transaction_qty) AS min_total_Revenue
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY product_type
ORDER BY min_total_Revenue ASC
LIMIT 1;

-------------------------------------------------------------------------
--14.Total sales generated by each product
-------------------------------------------------------------------------
SELECT product_category,
       SUM(unit_price * transaction_qty) AS product_revenue
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY product_category
ORDER BY product_revenue DESC;

-------------------------------------------------------------------------
--15.Total sales generated 
-------------------------------------------------------------------------
SELECT SUM(unit_price * transaction_qty) AS Total_Revenue
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

--CUSTOMER BEHAVIOUR ANALYSIS
-------------------------------------------------------------------------
---16.Count thenumber of sales in each store per month
-------------------------------------------------------------------------

SELECT store_location,
       MONTH(transaction_date) AS sales_month,
       COUNT(*) AS number_of_sales
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY store_location, MONTH(transaction_date)
ORDER BY store_location;

-------------------------------------------------------------------------
--17.Total quantity of items sold per product category
-------------------------------------------------------------------------
SELECT DISTINCT product_category,
                SUM (transaction_qty) AS total_qty
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY product_category
ORDER BY total_qty DESC;

-------------------------------------------------------------------------
--18.Which store sells the most units in each product category
-------------------------------------------------------------------------
SELECT store_location,
       product_category,
       SUM(transaction_qty) AS total_units_sold
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY store_location,product_category
ORDER BY total_units_sold DESC;

---------------------------------------------------------------------------------------
--19.Identify earliest and late times, earliest time is 06:00AM and Late time is 20:59pm
----------------------------------------------------------------------------------------
SELECT MIN (transaction_time) AS Early_morning 
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

---------------------------------------------------------------------------------------
--20.Identify  latest times, Latest time is 20:59pm
----------------------------------------------------------------------------------------
SELECT MAX (transaction_time) AS late_evening_hours
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`;

---------------------------------------------------------------------------------------
--21.Grouping time into buckets of hourly intervals
---------------------------------------------------------------------------------------
SELECT 
    product_category,
    CASE
        WHEN HOUR(transaction_time) BETWEEN 6 AND 8 THEN 'Early Morning Rush'
        WHEN HOUR(transaction_time) BETWEEN 9 AND 11 THEN 'Mid Morning'
        WHEN HOUR(transaction_time) BETWEEN 12 AND 15 THEN 'Afternoon'
        WHEN HOUR(transaction_time) BETWEEN 16 AND 17 THEN 'Late Afternoon Rush'
        WHEN HOUR(transaction_time) BETWEEN 18 AND 19 THEN 'Evening'
        ELSE 'Night'
    END AS transaction_time_bucket,
    COUNT(product_id) AS total_products
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY 
    product_category,
    CASE
        WHEN HOUR(transaction_time) BETWEEN 6 AND 8 THEN 'Early Morning Rush'
        WHEN HOUR(transaction_time) BETWEEN 9 AND 11 THEN 'Mid Morning'
        WHEN HOUR(transaction_time) BETWEEN 12 AND 15 THEN 'Afternoon'
        WHEN HOUR(transaction_time) BETWEEN 16 AND 17 THEN 'Late Afternoon Rush'
        WHEN HOUR(transaction_time) BETWEEN 18 AND 19 THEN 'Evening'
        ELSE 'Night'
    END
ORDER BY total_products DESC;

---------------------------------------------------------------------------------------
--22.What time of day the store performs best 
---------------------------------------------------------------------------------------
SELECT DISTINCT store_location,
                product_category,
    CASE
        WHEN HOUR(transaction_time) BETWEEN 6 AND 8 THEN 'Early Morning Rush'
        WHEN HOUR(transaction_time) BETWEEN 9 AND 11 THEN 'Mid Morning'
        WHEN HOUR(transaction_time) BETWEEN 12 AND 15 THEN 'Afternoon'
        WHEN HOUR(transaction_time) BETWEEN 16 AND 17 THEN 'Late Afternoon Rush'
        WHEN HOUR(transaction_time) BETWEEN 18 AND 19 THEN 'Evening'
        ELSE 'Night'
    END AS transaction_time_bucket,
    SUM(transaction_qty*unit_price) AS total_amount
FROM `brightlight`.`default`.`bright_coffee_shop_analysis`
GROUP BY 
    store_location,
    product_category,
    CASE
        WHEN HOUR(transaction_time) BETWEEN 6 AND 8 THEN 'Early Morning Rush'
        WHEN HOUR(transaction_time) BETWEEN 9 AND 11 THEN 'Mid Morning'
        WHEN HOUR(transaction_time) BETWEEN 12 AND 15 THEN 'Afternoon'
        WHEN HOUR(transaction_time) BETWEEN 16 AND 17 THEN 'Late Afternoon Rush'
        WHEN HOUR(transaction_time) BETWEEN 18 AND 19 THEN 'Evening'
        ELSE 'Night'
    END
ORDER BY total_amount DESC;
        
